### ISSUE TITLE
Copyright notice to [current year]

### ISSUE THREAD

**Issue by martinstabe** [ft-interactive/starter-kit#10]
The default copyright in the footer says 2015. The default ReadMe.md licence/copyright notice should be the same as this one, which has been approved by the legal dept: https://github.com/ft-interactive/guffipedia/blob/master/README.md

**Comment by kavanagh** [comment]
I've updated the existing hard-coded year to be 2016. Setting it to the current year can be something that build-time templates can handle, once they are available.

Regarding the content copyright I've made a note on #7
