### ISSUE TITLE
Update to the latest Origami deps

### ISSUE THREAD

**Issue by aendrew** [ft-interactive/starter-kit#117]
There's a major version bump to ~30 Origami components due to bumping `o-colors` and `o-typography`. I think the `o-typography` update includes a fix to Metric that restores its baseline, which is reason alone to do this.

**Comment by joannaskao** [comment]
We should make sure to time this with color changes on the main FT — bumping up o-colors and o-typography to the latest versions (I think) means changing the body background to `#fff1e5`, etc...

**Comment by davidbjourno** [comment]
Has this been scheduled yet? The rest of the site is starting to look markedly different to a default starter kit page.

**Comment by aendrew** [comment]
@davidbjourno We start a new sprint on Wednesday, I'll make sure it gets prioritised.

**Comment by aendrew** [comment]
Fixed by @callumlocke in a36402e9b3b18f00938c140db6b8d0ee911d274c.

**Comment by davidbjourno** [comment]
Could we have the appropriate o-typography classes added to `article-head.html`, please? So far I've noticed we're missing `.o-typography-standfirst` and `.o-typography-author` at least, and our byline markup needs updating to account for the new styling.
