### ISSUE TITLE
Change Old Pink to the New Pink

### ISSUE THREAD

**Issue by ajwl** [ft-interactive/starter-kit#128]
The old pink is #fff1e0
Search and replace to #fff1e5

**Comment by aendrew** [comment]
Before this happens I think we need to ensure all of our Origami deps are updated to the latest versions, or maybe this should also be done in addition to doing the global find/replace.

**Comment by callumlocke** [comment]
In theory this is just a matter of depending directly on the latest o-colors. Then bower's resolution system will tell us if there's any problems.
