### ISSUE TITLE
Installer script doesn't install dev dependencies

### ISSUE THREAD

**Issue by joannaskao** [ft-interactive/starter-kit#146]

**Comment by aendrew** [comment]
@callumlocke Do you think it could be [this line](https://github.com/ft-interactive/starter-kit/blob/master/configure#L89) causing this?

**Comment by callumlocke** [comment]
causing it how?

**Comment by callumlocke** [comment]
i've changed it to just `npm install`, the `--link` is just an optimisation and not necessary. let's see if that fixes it.
