### ISSUE TITLE
Document .netrc requirement

### ISSUE THREAD

**Issue by aendrew** [ft-interactive/starter-kit#156]
At present there is no documentation about setting up `.netrc`.

**Comment by notlee** [comment]
https://github.com/ft-interactive/starter-kit/blob/db7fe1ee1dbfb18d99ee1e952dff8f0ce26dea0e/configure#L94

**Comment by notlee** [comment]
After configuring `.netrc` I continued to receive the following error, although removing `team_id` from the curl request circumvented it.

>You need admin access to the team before adding a repository to it.

It appears that creating the new repository might have failed as I'm not a maintainer of the [Developers team](https://github.com/orgs/ft-interactive/teams/developers/members) and therefore unable to create a repository for the team. 
https://github.com/ft-interactive/starter-kit/blob/db7fe1ee1dbfb18d99ee1e952dff8f0ce26dea0e/configure#L94
