### ISSUE TITLE
Update to pa11y version using headless chrome via Puppetter

### ISSUE THREAD

**Issue by joannaskao** [ft-interactive/starter-kit#165]
Keep an eye out for v5 (https://github.com/pa11y/pa11y), which will use headless chrome instead of PhantomJS, which has been failing a number of our builds

**Comment by aendrew** [comment]
Feel free to start on the migration path to the beta version of that if it seems stable enough, I'd love to get rid of PhantomJS.

**Comment by joannaskao** [comment]
Fixed with #187. Thanks @aendrew!!
