### ISSUE TITLE
Watch/reload config and views folders

### ISSUE THREAD

**Issue by joannaskao** [ft-interactive/starter-kit#172]
Can we get webpack to watch and reload when changes are made to the `config` and `views` folders the same way it reloads when changes are made to the `client` folder?

**Comment by aendrew** [comment]
@joannaskao Yes and no — I can add something like [Chokidar](https://www.npmjs.com/package/chokidar) to restart `webpack-dev-server` upon file modification in either of those folders, but AFAICT it's not possible to do so via hot reload.
