### ISSUE TITLE
Spacing btw kicker and story title inconsistent with FT.com

### ISSUE THREAD

**Issue by cnev177** [ft-interactive/starter-kit#186]
Starter kit
![image](https://user-images.githubusercontent.com/2536516/38820433-cda2d440-4195-11e8-914b-336180b9d8e6.png)

FT.com
![image](https://user-images.githubusercontent.com/2536516/38820293-667f2c46-4195-11e8-9b81-1965861ad89d.png)

**Comment by kavanagh** [comment]
Use o-topper instead

**Comment by cnev177** [comment]
Thanks @kavanagh The problem I realise is because we don't have "Add to myFT" feature on the starter kit. So that is why the kicker has been placed further from the title. Is o-topper in the origami docs?

**Comment by aendra-rininsland** [comment]
Closing as `woefully outdated`
