### ISSUE TITLE
Remove o-grid; replace with CSS grid layout

### ISSUE THREAD

**Issue by aendra-rininsland** [ft-interactive/starter-kit#192]
If Next eschews o-grid for CSS grid I'm all for totally doing the same. 

### Benefits:

* One less Origami dep
* No more weird o-grid syntax (and resultant DOM pollution)
* Implementation more in line with web standards
* Resulting output closer to Next
* CSS grid layout is really powerful

**Comment by aendrew** [comment]
@cnev177 Any idea about Joanna's question?

**Comment by aendra-rininsland** [comment]
Closing as `woefully outdated`
