### ISSUE TITLE
Series navigation implementation

### ISSUE THREAD

**Issue by martinstabe** [ft-interactive/starter-kit#197]
Requested by Claire Barron on Weekend. Add series navigation strip to starter kit page. This would allow Weekend to use IG pages more prominently.

eg

![screen shot 2018-05-22 at 16 51 42](https://user-images.githubusercontent.com/998519/40374176-75958024-5de0-11e8-99fb-3bbfef49ee1e.png)

**Comment by joannaskao** [comment]
I don't think we should be using our resources to duplicate article templates, especially when there are plans to be able to do more of our work in the CMS coming up. I think there are ways to link to other articles in series without needing to re-create the series navigation.

**Comment by aendrew** [comment]
Granted this would be pretty easy to do using React Router (ignoring the issues hosting that) in V2.

Marking as V2 for now while issue is still open.

**Comment by aendra-rininsland** [comment]
Closing a `wontfix` because this will be handled by ccc.
