### ISSUE TITLE
Sass edits don't cause refresh

### ISSUE THREAD

**Issue by aendra-rininsland** [ft-interactive/starter-kit#234]
For some reason webpack-dev-server isn't picking up Sass changes, at least when made in a file imported by main.scss.

**Comment by aendrew** [comment]
Update: setting `devServer.inline` to true and `devServer.hot` to `false` forces a reload and seems to solve the issue and forces a whole page reload.

This is suboptimal however as it takes a long time to do a full compile and reloading the page hampers DX.

A solution seems to be to conditionally use style-loader in development and MiniCssExtractPlugin.loader in production. I tried this on my current project, however, and all the o-grid Sass broke.
