### ISSUE TITLE
Create repository with team

### ISSUE THREAD

**Issue by NargiT** [ft-interactive/starter-kit#237]
Hello,
I would like to create a repository with a githubapp and assign a given team to it.
According to the documentation it is possible with (GitHub Enterprise Server 2.16.0) for an organisation (https://developer.github.com/enterprise/2.16/v3/repos/#create).

I can create a repository inside the org without a team (it works) but when I add the teamid to the payload I get the following error. 
```
422 
You need admin access to the team before adding a repository to it. https://developer.github.com/enterprise/2.16/v3/repos/#create
```

**Comment by aendrew** [comment]
What are you trying to do, exactly? Also, this project is very Financial Times-specific, I'm not sure what value you're trying to get from it?

Let me know and I'll possibly reopen.
