### ISSUE TITLE
Figure out why some component names are different in production

### ISSUE THREAD

**Issue by davidbjourno** [ft-interactive/starter-kit#247]
E.g. `<App />` becomes `<h />`.

**Comment by aendrew** [comment]
Isn't this just minification? If you set the `.displayName` property of a component it'll show up in dev tools as that in prod instead of the minified version.

If I'm wrong about this lmk and I'll reopen.

**Comment by davidbjourno** [comment]
As discussed, @aendrew to research use of [babel-plugin-add-react-displayname](https://www.npmjs.com/package/babel-plugin-add-react-displayname) to bring Starter Kit more into alignment with g-components.

**Comment by aendra-rininsland** [comment]
Closing as `woefully outdated`
