### ISSUE TITLE
Make HTML pages with an app

### ISSUE THREAD

**Issue by kavanagh** [ft-interactive/starter-kit#27]
Remove the Gulp tasks in favour of an app that make equivalent html pages. Instead have a task that can mirror (save all) routes to HTML files. Also have a Procfile and extras to enable the app to be pushed to heroku

**Comment by aendrew** [comment]
@kavanagh Has this been started yet? Am happy to do so if not. :+1:

**Comment by aendrew** [comment]
See #34.

**Comment by aendrew** [comment]
:-1: Probably not taking this approach. Closing.
