### ISSUE TITLE
Build-time templates

### ISSUE THREAD

**Issue by kavanagh** [ft-interactive/starter-kit#5]
See ft-interactive/books as a starting place.

Use Nunjucks.

What to do about client-side templates now?

**Comment by aendrew** [comment]
@kavanagh re: client-side templating, do you mean trying to create some webcomponent-y infrastructure for the Origami markup, or create Nunjucks templates for client-side code?

If the former, I did a bit of research at the beginning of working on `ig-article`, which I'll summarise below:

- [**Polymer:**](https://www.polymer-project.org/1.0/)
  - :+1: Very nice and simple syntax; very forwarding-thinking implementation. HTML, CSS and JS for component contained in a single HTML file. Incredibly easy to make work as a progressive web-app. 
  - :-1: Heavy footprint, only reliable in IE11+ (Safari is a pain), uses Bower for dep management. HTML modules are :hankey:.
- [**React:**](https://facebook.github.io/react/)
  - :+1: Fairly light, fast, good for ~IE10, can server-side render, uses normal JS modules
  - :-1: The least intuitive/familiar syntax for most people in the newsroom.
- [**Knockout:**](http://knockoutjs.com/documentation/component-overview.html)
  - :+1: Support going back to IE6, very light, custom elements
  - :-1: No custom attributes; all component config is done via JSON string in `params` attribute. I haven't used it ever.
- [**RiotJS:**](http://riotjs.com)
  - :+1: Support to IE9, nice syntax, templates can be compiled server-side, very fast, small footprint, designed to play nicely with jQuery. Single template file can contain HTML/JS/CSS. Nice syntax.
  - :-1: I haven't used it for anything.

**Comment by kavanagh** [comment]
Thanks for doing the research. I did take a look at the work you did on ig-article, it was interesting to see the comparison.

I think all the above options are too much for us to conquer at this moment in time because the effort needed to migrate to the approach and for everyone to learn enough to become productive.

In short my feeling is native web components might be the dream but a mix of Nunjucks and React is probably the most practical in the near future. Let's see how we bed in with this small amount of templating and the move to ig-article.
