### ISSUE TITLE
Replace node-git with git-js?

### ISSUE THREAD

**Issue by aendrew** [ft-interactive/starter-kit#57]
I've recently gotten a few errors when compiling nodegit on Node 7+, seems updating the dependency to `@latest` resolves the issue.

**Comment by aendrew** [comment]
Another idea — NodeGit is annoying because it needs to be compiled. This just leverages the local git binary and is much, much lighter: https://github.com/steveukx/git-js

**Comment by tomgp** [comment]
that seems good assuming there is a local git binary. I can't think of an environment where that's not going to be the case...
