### ISSUE TITLE
.article-body > :not(.graphic) class casuing misalignment

### ISSUE THREAD

**Issue by sdbernard** [ft-interactive/starter-kit#58]
This class which is applied to everything inside the article-body div causes misalignment when the an element's font-size is different to the body itself

.article-body > :not(.graphic) {
   max-width: 625px;
   margin: 1em auto;
   padding: 0 0.75em;
}

I think this could be simply solved using rem instead of em?

If for example you add an h2 in the body it makes the padding too much because of the larger font-size...

![image](https://cloud.githubusercontent.com/assets/2511348/21933851/fd50b2a8-d99e-11e6-8ba9-752e2b4c89b7.png)

**Comment by aendrew** [comment]
This was fixed by @ajwl in #87.
