### ISSUE TITLE
Problems with 'setup' command and 'configure' script

### ISSUE THREAD

**Issue by callumlocke** [ft-interactive/starter-kit#69]
Both the setup script and the configure script assume SSH is available, so they don't work over wifi in OSB. I think this can be changed to HTTPS without problems.

Also, the configure script doesn't handle a 401 Unauthorized response from GitHub's API when creating the repo (and probably other kinds of failure) – it ploughs on to the next step assuming the repo has been created successfully.

**Comment by aendrew** [comment]
@callumlocke Agreed re: changing to HTTPS.

With regards to 401 unauthorized and other failures, I feel this is probably by-design — the more likely error thrown by GitHub's API is insufficient private repos, which itself shouldn't prevent scaffolding (particularly if the configure script has already created a folder and pulled down deps).

**Comment by aendrew** [comment]
Closing because SSH works in OSB now.
