### ISSUE TITLE
Preflight tests prevent CI deployment

### ISSUE THREAD

**Issue by callumlocke** [ft-interactive/starter-kit#70]
Currently, if you don't fill in certain details like the Twitter meta description, preflight fails, and the project won't deploy. So if you're just prototyping something that _might_ get published at some point, you have to fill these fields with junk if you want to get your deploy workflow up and running. It is not reasonable to expect someone to come up with valid contents for these things when a project is at an experimental stage.

I think we should stop blocking the CI build for these preflight checks. Then we should consider a way of doing these kind of checks as part of a publishing checklist, ie at the point when a project is made public through the IG server.

**Comment by aendrew** [comment]
I partially agree. Preflight tests are used both to ensure best practices (all metadata filled in) but also provide a way of assuring CI doesn't publish broken content. 

That said, the likelihood that somebody will fill in nonsense to ensure an early build succeeds that then gets forgotten is a fairly reasonable concern. This utterly undermines the whole "ensuring best practices" aim of the tests.

I'd say a half-way solution would be ideal: fail production builds, warn for development builds.

**Comment by aendrew** [comment]
Additionally: author metatag seems to have disappeared and is failing everything, and the related content test seems broken.

**Comment by martinstabe** [comment]
See also timestamp test.

**Comment by aendrew** [comment]
This should be fixed by #85.
