### ISSUE TITLE
Fix build service use throughout

### ISSUE THREAD

**Issue by callumlocke** [ft-interactive/starter-kit#79]
Looks like there are several more weird exports like the one fixed by #78. Plus other cleanup jobs.

- [ ] Do a search for `export=` and remove this param from all build service script URLs, so they all hang things on the default `Origami` global instead. For each one, fix any weird accompanying code that was relying on the weird global (e.g. `new oComments['o-comments'](comments, { ... })`
  - NB check for answer to [this](https://github.com/Financial-Times/origami-build-service/issues/118) before doing this
- [ ] Update all build service URLs to use the new `__origami` URL format (both scripts and stylesheets).
- [ ] If there are any image service URLs (not sure), update those to new `__origami` format too.
- [ ] remove `async` attribute from all inline scripts, as this is not a thing.

**Comment by aendrew** [comment]
Resolved by #90.
