### ISSUE TITLE
Look into ways of dealing with conflicting dependencies in Origami build service

### ISSUE THREAD

**Issue by joannaskao** [ft-interactive/starter-kit#94]
Now that we're using one build service URL for all Origami build service modules, none of them load if there are conflicting dependencies (for example: https://www.ft.com/__origami/service/build/v2/bundles/css?modules=o-normalise@%5E1,o-fonts@%5E2,o-grid@%5E4.2.1,o-typography@%5E4.3.1,o-header@%5E6.5.1,g-audio@%5E1.0.2,o-card@%5E2.1.8,o-footer@%5E5.0.3,o-comments@%5E3.2.0,o-share@%5E3).

**Comment by aendrew** [comment]
This is actually a good thing, as it prevents conflicting components from appearing on page. Problems will appear far sooner in development and can be resolved according.

I think the bigger issue is it's possible our Origami components are out of date. If only there was _some tool out there_ that enabled easy updates and resolution of module dependencies...

**Comment by aendrew** [comment]
@joannaskao I've investigated a bit more, seems Starter Kit is currently using the latest version of everything. Would it be possible to downgrade g-audio to `o-icons@^4`?

**Comment by aendrew** [comment]
This isn't really as relevant to Starter Kit as it is to `g-audio`, closing. That said, updating to newer `o-icons` in `g-audio` might be possible/necessary post-#117.
